language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- make check
- make unittest
- make clean
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: NNaCl2oAfahWe5/nQ+C4QWznkOOfZNdhfJbywHnvW6GlP1VDAeKO+Ae8OKYNhwIU3WV3XdFuMUCruTZTlhMCgLxqDfz1oJFtUk1leOoKXH4s1LpsuIm0T0DD6mMwPdbYHJfDWJqmbhzAsQ/1DP/u7V36BKQMyAAf5aYq5iG85ng=
  on:
    branch: master
    python: 2.7
  app:
    master: groceries-api
  run:
  - make migrate
after_success:
  coverage
notifications:
  email: false
