language: python
python:
- 2.7
- 3.3
- 3.4
install:
- pip install -e ".[dev]"
script:
- make check
- make unittest
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: NNaCl2oAfahWe5/nQ+C4QWznkOOfZNdhfJbywHnvW6GlP1VDAeKO+Ae8OKYNhwIU3WV3XdFuMUCruTZTlhMCgLxqDfz1oJFtUk1leOoKXH4s1LpsuIm0T0DD6mMwPdbYHJfDWJqmbhzAsQ/1DP/u7V36BKQMyAAf5aYq5iG85ng=
  on:
    branch: master
    python: 2.7
  app:
    master: groceries-api
  run:
  - alembic upgrade head
after_success:
  coveralls
notifications:
  email: false
